theme: jekyll-theme-cayman
title: [B. C. Chap]
description: [Data-Driven Problem Solver | Diversity Equity and Inclusion Advocate | Recent Physics Grad\
[linkedin](https://www.linkedin.com/in/bcchap/) | [github](https://github.com/bcchap) | [resume](https://github.com/bcchap)]
